### ISSUE TITLE
LOGOについて

### ISSUE THREAD

**Issue by YIFAN-888** [YIFAN-888/GRP_1#6]
- LOGOを作ります
- 4人で一つずつ提案する

**Comment by YIFAN-888** [comment]
> 
![image](https://user-images.githubusercontent.com/84076319/127253715-7a9e211a-2c52-49aa-bc02-e36d4b28ec6c.png)

**Comment by wanghaibo325** [comment]
[logo (1).zip](https://github.com/YIFAN-888/GRP_1/files/6889973/logo.1.zip)

**Comment by wanghaibo325** [comment]
``
![logo](https://user-images.githubusercontent.com/84367207/127256730-9e5e0db3-8f5e-4d03-a305-316a85cd791c.jpg)

**Comment by YIFAN-888** [comment]
[
![twitter_header_photo_2](https://user-images.githubusercontent.com/84076319/127265467-f871e4c5-7593-4f23-8644-3243889118c7.png)
](url)

**Comment by YIFAN-888** [comment]
[
![facebook_profile_image](https://user-images.githubusercontent.com/84076319/127265516-f1794810-e2fc-4da8-831f-a5f41f700c2a.png)
](url)

**Comment by YIFAN-888** [comment]
[
![pinterest_board_photo](https://user-images.githubusercontent.com/84076319/127586574-0cfa2d50-523a-4e8c-bd8d-d05a7586651e.png)
](url)

**Comment by zhangqian19890419** [comment]
[
![unnamed](https://user-images.githubusercontent.com/84367237/127789200-068bf89a-320f-49c3-ae95-0708fe1f5457.jpg)
](url)
